version: "3.8"

services:
  website:
    build: ./
    ports:
      - 5000:5000
#    environment:
#      DB_URL: jdbc:vertica://database/Vmart
#
#  database:
#    image: vertica/vertica-ce
#    ports:
#      - "5433:5433"
#    volumes:
#      - vertica_data:/data
#
#volumes:
#  vertica_data: