version: "3.9"

services:
  vertica:
    environment:
      APP_DB_USER: "dbadmin"
      APP_DB_PASSWORD: ""
      TZ: "Europe/Prague"
    container_name: vertica-ce
    image: vertica/vertica-ce
    ports:
      - "5433:5433"
      - "5444:5444"
    networks:
      - net
#    deploy:
#      mode: global

    volumes:
      - type: volume
        source: vertica-data2
        target: /data

  website:
    build: ./
    ports:
      - "5000:5000"
    networks:
      - net
    environment:
      DB_HOST: vertica
      DB_PORT: 5433

volumes:
  vertica-data2:

networks:
  net:
    driver: bridge