version: "3.9"

services:
  postgres:
    environment:
      APP_DB_USER: "postgres"
      APP_DB_PASSWORD: "postgres"
      TZ: "Europe/Prague"
    build: ./database/
#    container_name: vertica-ce
#    image: vertica/vertica-ce
    ports:
      - "5432:5432"
#      - "5444:5444"
    networks:
      - net
#    deploy:
#      mode: global

    volumes:
      - type: volume
        source: postgres-data
        target: /data

  website:
    build: ./website/
    ports:
      - "5000:5000"
    networks:
      - net
    environment:
      DB_HOST: postgres
      DB_PORT: 5432

volumes:
  postgres-data:

networks:
  net:
    driver: bridge